# Generated by Django 5.2.3 on 2025-07-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('datetime', models.DateTimeField()),
                ('police_force', models.CharField(blank=True, max_length=100, null=True)),
                ('weather_conditions', models.CharField(max_length=50)),
                ('road_surface_conditions', models.CharField(max_length=50)),
                ('light_conditions', models.CharField(max_length=50)),
                ('number_of_vehicles', models.PositiveIntegerField()),
                ('number_of_casualties', models.PositiveIntegerField()),
                ('vehicle_types_involved', models.JSONField()),
                ('severity_score', models.FloatField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
